services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    hostname: oracle-db
#    restart: always
    ports:
      - "1521:1521"
      - "9090:8080"
    environment:
      ORACLE_SID: XE
      ORACLE_PWD: oracle
      ORACLE_USERNAME: system
      ORACLE_ALLOW_REMOTE: true
    volumes:
      - ./ora_data:/oradata/orcl